package com.example.ui.theme

object Localization {

    private val translations = mapOf(
        "ar" to mapOf(
            "app_name" to "منصة ABK TV",
            "home" to "الرئيسية",
            "search" to "البحث المتقدم",
            "creators" to "المجتمع والقصص",
            "wallet" to "المحفظة الرقمية",
            "creator_dashboard" to "لوحة صانع المحتوى",
            "admin_panel" to "إدارة المنصة",
            "verification" to "توثيق القنوات",
            "trending_movies" to "الأفلام الأكثر رواجاً",
            "trending_series" to "المسلسلات الموصى بها",
            "premium_tag" to "بريميوم VIP",
            "continue_watching" to "متابعة المشاهدة",
            "recommended" to "مقترحات حصرية لك",
            "creators_feed" to "قصص صناع المحتوى الآن",
            "settings" to "إعدادات اللغة",
            "watch_now" to "شاهد الآن 🍿",
            "add_watchlist" to "حفظ بالقائمة",
            "direct_message" to "مراسلة فورية",
            "deposit" to "شحن رصيد",
            "withdraw" to "سحب نقدي",
            "current_balance" to "الرصيد المتوفر",
            "premium_sub_plans" to "عروض الاشتراكات المميزة",
            "buy_sub" to "اشتراك الآن",
            "identity_verification" to "طلب شارة التوثيق الزرقاء",
            "verified_badge" to "موثق",
            "watch_time" to "ساعات المشاهدة",
            "creator_earnings" to "أرباح القناة",
            "publish_title" to "نشر محتوى جديد",
            "dismiss" to "تجاهل",
            "reports" to "البلاغات المفتوحة",
            "global_stats" to "إحصائيات المنصة العامة",
            "broadcast_notice" to "بث إشعار عام للمشتركين",
            "play_sim" to "مشغل الفيديو السينمائي",
            "subtitles" to "الترجمة المصاحبة",
            "sub_size" to "حجم الخط",
            "sub_color" to "لون الخط",
            "comments" to "التعليقات والمناقشات",
            "rating" to "التقييم العام",
            "submit" to "إرسال",
            "placeholder_comment" to "اكتب تعليقك هنا بكل أدب...",
            "placeholder_review" to "اكتب مراجعتك التفصيلية للأعضاء...",
            "review_title" to "عنوان المراجعة",
            "download" to "تنزيل الآن",
            "downloaded" to "تم التنزيل بنجاح",
            "sim_offline" to "تنزيل للمشاهدة بدون إنترنت",
            "seasons" to "المواسم المتوفرة",
            "episodes" to "الحلقات المدرجة",
            "followers" to "متابع",
            "following" to "يتابع",
            "send_message" to "إرسال رسالة...",
            "typing" to "يكتب الآن رداً...",
            "submit_verification_btn" to "تقديم المستندات للتدقيق المباشر",
            "fullname" to "الاسم الكامل القانوني",
            "doc_type" to "نوع مستند التوثيق الرئيسي"
        ),
        "en" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Home",
            "search" to "Advanced Search",
            "creators" to "Community & Stories",
            "wallet" to "Digital Wallet",
            "creator_dashboard" to "Creator Dashboard",
            "admin_panel" to "Admin Control",
            "verification" to "Channel Verification",
            "trending_movies" to "Trending Movies",
            "trending_series" to "Recommended Series",
            "premium_tag" to "Premium VIP",
            "continue_watching" to "Continue Watching",
            "recommended" to "Recommended For You",
            "creators_feed" to "Active Creator Stories",
            "settings" to "Language Settings",
            "watch_now" to "Watch Now 🍿",
            "add_watchlist" to "Add to Watchlist",
            "direct_message" to "Direct Message",
            "deposit" to "Deposit Funds",
            "withdraw" to "Withdraw",
            "current_balance" to "Available Balance",
            "premium_sub_plans" to "Premium VIP Subscription Plans",
            "buy_sub" to "Subscribe Now",
            "identity_verification" to "Apply for Blue Verified Badge",
            "verified_badge" to "Verified",
            "watch_time" to "Watch Time Hours",
            "creator_earnings" to "Creator Earnings",
            "publish_title" to "Publish New Content",
            "dismiss" to "Dismiss",
            "reports" to "Pending Fraud Reports",
            "global_stats" to "Platform Global Statistics",
            "broadcast_notice" to "Broadcast Global Notice",
            "play_sim" to "Cinematic Video Player",
            "subtitles" to "Subtitles / Captions",
            "sub_size" to "Font Size",
            "sub_color" to "Font Color",
            "comments" to "Comments & Chat Forum",
            "rating" to "IMDb Rating",
            "submit" to "Submit",
            "placeholder_comment" to "Write your interactive comment here...",
            "placeholder_review" to "Write your absolute cinematic review...",
            "review_title" to "Review Headline",
            "download" to "Download Offline",
            "downloaded" to "Downloaded Successfully",
            "sim_offline" to "Download movie to offline memory",
            "seasons" to "Available Seasons",
            "episodes" to "Listed Episodes",
            "followers" to "followers",
            "following" to "following",
            "send_message" to "Send private message...",
            "typing" to "is typing response...",
            "submit_verification_btn" to "Submit Documents to Admins",
            "fullname" to "Legal Corporate Name",
            "doc_type" to "Primary Verification Document"
        ),
        "fr" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Accueil",
            "search" to "Recherche",
            "creators" to "Créateurs",
            "wallet" to "Portefeuille",
            "creator_dashboard" to "Tableau de Bord",
            "admin_panel" to "Panneau Admin",
            "verification" to "Vérification",
            "trending_movies" to "Films Tendances",
            "trending_series" to "Séries Recommandées",
            "premium_tag" to "Premium VIP",
            "continue_watching" to "Continuer la lecture",
            "recommended" to "Recommandé pour vous",
            "creators_feed" to "Stories des Créateurs",
            "settings" to "Langues",
            "watch_now" to "Regarder 🍿",
            "add_watchlist" to "Ajouter à ma liste",
            "direct_message" to "Message Direct",
            "deposit" to "Déposer des fonds",
            "withdraw" to "Retirer de l'argent",
            "current_balance" to "Solde disponible",
            "premium_sub_plans" to "Abonnements Premium VIP",
            "buy_sub" to "S'abonner maintenant",
            "identity_verification" to "Demander le badge bleu",
            "verified_badge" to "Vérifié",
            "watch_time" to "Heures de visionnage",
            "creator_earnings" to "Gains du créateur",
            "publish_title" to "Publier du contenu",
            "dismiss" to "Ignorer",
            "reports" to "Rapports d'abus",
            "global_stats" to "Statistiques globales",
            "broadcast_notice" to "Diffuser une notification",
            "play_sim" to "Lecteur Vidéo",
            "subtitles" to "Sous-titres",
            "sub_size" to "Taille de police",
            "sub_color" to "Couleur",
            "comments" to "Commentaires",
            "rating" to "Note globale",
            "submit" to "Envoyer",
            "placeholder_comment" to "Écrivez votre commentaire...",
            "placeholder_review" to "Écrivez votre critique...",
            "review_title" to "Titre de l'avis",
            "download" to "Télécharger",
            "downloaded" to "Téléchargé avec succès",
            "sim_offline" to "Télécharger pour regarder hors ligne",
            "seasons" to "Saisons disponibles",
            "episodes" to "Épisodes répertoriés",
            "followers" to "abonnés",
            "following" to "abonnements",
            "send_message" to "Envoyer un message...",
            "typing" to "écrit une réponse...",
            "submit_verification_btn" to "Soumettre les documents",
            "fullname" to "Nom légal complet",
            "doc_type" to "Type de document"
        ),
        "de" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Startseite",
            "search" to "Suche",
            "creators" to "Community",
            "wallet" to "Geldbörse",
            "creator_dashboard" to "Creator-Studio",
            "admin_panel" to "Admin-Bereich",
            "verification" to "Verifizierung",
            "trending_movies" to "Beliebte Filme",
            "trending_series" to "Empfohlene Serien",
            "premium_tag" to "Premium VIP",
            "continue_watching" to "Weitersehen",
            "recommended" to "Für dich empfohlen",
            "creators_feed" to "Aktive Creator-Storys",
            "settings" to "Spracheinstellungen",
            "watch_now" to "Jetzt ansehen 🍿",
            "add_watchlist" to "Auf die Merkliste",
            "direct_message" to "Direktnachricht",
            "deposit" to "Guthaben aufladen",
            "withdraw" to "Auszahlen",
            "current_balance" to "Guthaben",
            "premium_sub_plans" to "Premium VIP-Abonnements",
            "buy_sub" to "Jetzt abonnieren",
            "identity_verification" to "Blaues Abzeichen beantragen",
            "verified_badge" to "Verifiziert",
            "watch_time" to "Wiedergabezeit (Std.)",
            "creator_earnings" to "Creator-Einnahmen",
            "publish_title" to "Inhalt veröffentlichen",
            "dismiss" to "Verwerfen",
            "reports" to "Ausstehende Berichte",
            "global_stats" to "Globale Statistiken",
            "broadcast_notice" to "Ankündigung senden",
            "play_sim" to "Videoplayer",
            "subtitles" to "Untertitel",
            "sub_size" to "Schriftgröße",
            "sub_color" to "Schriftfarbe",
            "comments" to "Kommentare",
            "rating" to "Bewertung",
            "submit" to "Senden",
            "placeholder_comment" to "Kommentar verfassen...",
            "placeholder_review" to "Rezension schreiben...",
            "review_title" to "Titel der Rezension",
            "download" to "Herunterladen",
            "downloaded" to "Erfolgreich heruntergeladen",
            "sim_offline" to "Für Offline-Wiedergabe herunterladen",
            "seasons" to "Verfügbare Staffeln",
            "episodes" to "Episoden",
            "followers" to "Follower",
            "following" to "Folge ich",
            "send_message" to "Nachricht senden...",
            "typing" to "tippt eine Antwort...",
            "submit_verification_btn" to "Dokumente einreichen",
            "fullname" to "Vollständiger Name",
            "doc_type" to "Dokumenttyp"
        ),
        "it" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Home",
            "search" to "Cerca",
            "creators" to "Community",
            "wallet" to "Portafoglio",
            "creator_dashboard" to "Studio Creator",
            "admin_panel" to "Admin",
            "verification" to "Verifica",
            "trending_movies" to "Film di tendenza",
            "trending_series" to "Serie consigliate",
            "premium_tag" to "Premium VIP",
            "continue_watching" to "Continua a guardare",
            "recommended" to "Consigliati per te",
            "creators_feed" to "Storie dei Creator",
            "settings" to "Lingua",
            "watch_now" to "Guarda ora 🍿",
            "add_watchlist" to "Aggiungi alla lista",
            "direct_message" to "Messaggio diretto",
            "deposit" to "Deposita fondi",
            "withdraw" to "Preleva",
            "current_balance" to "Saldo disponibile",
            "premium_sub_plans" to "Abbonamento Premium VIP",
            "buy_sub" to "Abbonati ora",
            "identity_verification" to "Richiedi badge blu",
            "verified_badge" to "Verificato",
            "watch_time" to "Ore di visione",
            "creator_earnings" to "Guadagni canale",
            "publish_title" to "Pubblica nuovo contenuto",
            "dismiss" to "Ignora",
            "reports" to "Segnalazioni pending",
            "global_stats" to "Statistiche generali",
            "broadcast_notice" to "Invia notifica globale",
            "play_sim" to "Riproduttore Video",
            "subtitles" to "Sottotitoli",
            "sub_size" to "Dimensione testo",
            "sub_color" to "Colore testo",
            "comments" to "Commenti",
            "rating" to "Voto IMDb",
            "submit" to "Invia",
            "placeholder_comment" to "Scrivi commento...",
            "placeholder_review" to "Scrivi una recensione...",
            "review_title" to "Titolo della recensione",
            "download" to "Scarica offline",
            "downloaded" to "Scaricato con successo",
            "sim_offline" to "Scarica nella memoria locale",
            "seasons" to "Stagioni disponibili",
            "episodes" to "Episodi",
            "followers" to "follower",
            "following" to "seguiti",
            "send_message" to "Invia messaggio...",
            "typing" to "sta scrivendo..."
        ),
        "pt" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Início",
            "search" to "Pesquisa",
            "creators" to "Comunidade",
            "wallet" to "Carteira",
            "creator_dashboard" to "Painel do Criador",
            "admin_panel" to "Controle Administrativo",
            "verification" to "Verificação de Canal",
            "trending_movies" to "Filmes em Destaque",
            "trending_series" to "Séries Recomendadas",
            "premium_tag" to "Premium VIP",
            "continue_watching" to "Continuar Assistindo",
            "recommended" to "Recomendado para Você",
            "creators_feed" to "Stories dos Criadores",
            "settings" to "Configuração de Idioma",
            "watch_now" to "Assistir Agora 🍿",
            "add_watchlist" to "Minha Lista",
            "direct_message" to "Mensagem Direta",
            "deposit" to "Depositar Fundos",
            "withdraw" to "Retirar Fundos",
            "current_balance" to "Saldo Disponível",
            "premium_sub_plans" to "Subscrição Premium VIP",
            "buy_sub" to "Subscrever Agora",
            "identity_verification" to "Pedir Selo Azul de Autenticidade",
            "verified_badge" to "Verificado",
            "watch_time" to "Horas de reprodução",
            "creator_earnings" to "Ganhos Monetários",
            "publish_title" to "Publicar Novo Vídeo",
            "dismiss" to "Dispensar",
            "reports" to "Denúncias Pendentes",
            "global_stats" to "Estatísticas da Plataforma",
            "broadcast_notice" to "Emitir Alerta Global",
            "play_sim" to "Player de Vídeo",
            "subtitles" to "Legendas incorporadas",
            "sub_size" to "Tamanho do texto",
            "sub_color" to "Cor do texto",
            "comments" to "Seção de Comentários",
            "rating" to "Avaliação geral",
            "submit" to "Enviar",
            "placeholder_comment" to "Escreva um comentário amigável...",
            "placeholder_review" to "Escreva sua crítica completa...",
            "review_title" to "Título do Review",
            "download" to "Baixar Vídeo",
            "downloaded" to "Download Concluído",
            "sim_offline" to "Assistir offline",
            "seasons" to "Temporadas Disponíveis",
            "episodes" to "Episódios",
            "followers" to "seguidores",
            "following" to "seguindo",
            "send_message" to "Enviar mensagem...",
            "typing" to "está digitando resposta..."
        ),
        "ru" to mapOf(
            "app_name" to "ABK TV Premium",
            "home" to "Главный экран",
            "search" to "Расширенный поиск",
            "creators" to "Сообщество и Истории",
            "wallet" to "Цифровой Кошелек",
            "creator_dashboard" to "Панель Создателя",
            "admin_panel" to "Админка",
            "verification" to "Верификация аккаунта",
            "trending_movies" to "Популярные Фильмы",
            "trending_series" to "Рекомендуемые Сериалы",
            "premium_tag" to "Премиум VIP",
            "continue_watching" to "Продолжить просмотр",
            "recommended" to "Рекомендовано вам",
            "creators_feed" to "Активные Истории",
            "settings" to "Языковые настройки",
            "watch_now" to "Смотреть 🍿",
            "add_watchlist" to "В список",
            "direct_message" to "Написать ЛС",
            "deposit" to "Пополнить баланс",
            "withdraw" to "Вывести средства",
            "current_balance" to "Доступный Баланс",
            "premium_sub_plans" to "Премиум-подписки VIP",
            "buy_sub" to "Подписаться сейчас",
            "identity_verification" to "Запросить синюю птичку",
            "verified_badge" to "Верифицирован",
            "watch_time" to "Часы Просмотров",
            "creator_earnings" to "Доходы Канала",
            "publish_title" to "Опубликовать контент",
            "dismiss" to "Отклонить",
            "reports" to "Открытые жалобы",
            "global_stats" to "Общая статистика",
            "broadcast_notice" to "Разослать уведомление",
            "play_sim" to "Видеоплеер",
            "subtitles" to "Субтитры",
            "sub_size" to "Размер текста",
            "sub_color" to "Цвет",
            "comments" to "Комментарии и Обсуждения",
            "rating" to "Рейтинг IMDb",
            "submit" to "Отправить",
            "placeholder_comment" to "Напишите вежливый комментарий...",
            "placeholder_review" to "Напишите подробный разбор...",
            "review_title" to "Заголовок рецензии",
            "download" to "Скачать",
            "downloaded" to "Успешно скачано",
            "sim_offline" to "Скачать для офлайн-просмотра",
            "seasons" to "Доступные Сезоны",
            "episodes" to "Эпизоды",
            "followers" to "подписчиков",
            "following" to "подписок",
            "send_message" to "Написать...",
            "typing" to "печатает сообщение..."
        )
    )

    fun get(lang: String, key: String): String {
        return translations[lang]?.get(key) ?: translations["ar"]?.get(key) ?: key
    }
}
